"""Application configuration and data paths.

Settings are read from ``config.toml`` (in the JARVIS data directory) and then
overridden by environment variables prefixed with ``JARVIS_`` (nested fields use
``__`` as the delimiter, e.g. ``JARVIS_LLM__PLANNER_MODEL``). No secrets are ever
stored in configuration files - API keys live in the system credential store via
:mod:`jarvis.secrets`.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from platformdirs import PlatformDirs
from pydantic import BaseModel, ConfigDict
from pydantic_settings import BaseSettings, SettingsConfigDict, TomlConfigSettingsSource

APP_NAME = "jarvis"
APP_AUTHOR = "jarvis"

# Text written to a freshly generated config.toml by `jarvis init`. Model names
# are intentionally empty: they change frequently and must be chosen from the
# provider's current docs, never guessed (see docs/09_SETUP_AND_DEPENDENCIES.md).
DEFAULT_CONFIG_TOML = """\
# JARVIS configuration (non-secret settings). Generated by `jarvis init`.
config_version = 1

[llm]
planner_model = ""
fast_model = ""
vision_model = ""
provider_order = ["groq", "gemini"]
timeout_seconds = 30.0
max_retries = 3

[agent]
max_steps = 12
max_retries_per_step = 2
max_replans = 2
step_timeout_seconds = 30

[policy]
unlock_ttl_seconds = 300
password_max_failures = 5
lockout_seconds = 60
allowed_roots = ["~/Documents/JarvisWorkspace", "~/Desktop", "~/Downloads"]
delete_preview_threshold = 1
typed_confirmation_for_folders = true

[apps]
notepad = "notepad.exe"
calculator = "calc.exe"
chrome = "chrome.exe"

[daemon]
host = "127.0.0.1"
port = 0

[voice]
enabled = false
wake_word = "hey_jarvis"
stt_model = "base"
tts_backend = "piper"
silence_threshold = 0.01
silence_timeout_s = 0.7
max_segment_s = 30.0
listen_timeout_s = 30.0
idle_timeout_s = 120.0
max_session_s = 1800.0
max_dictation_chars = 20000
"""


class LLMSettings(BaseModel):
    """LLM model roles and provider behaviour.

    Roles map to model names. Defaults are empty placeholders: choose the actual
    model names from the current provider documentation and set them in
    ``config.toml`` or via ``JARVIS_LLM__*`` environment variables.
    """

    planner_model: str = ""
    fast_model: str = ""
    vision_model: str = ""
    provider_order: list[str] = ["groq", "gemini"]
    timeout_seconds: float = 30.0
    max_retries: int = 3


class AgentSettings(BaseModel):
    """LangGraph agent caps (used from Phase 1 onwards)."""

    max_steps: int = 12
    max_retries_per_step: int = 2
    max_replans: int = 2
    step_timeout_seconds: int = 30


class PolicySettings(BaseModel):
    """Permission/policy settings (used from Phase 1 onwards)."""

    unlock_ttl_seconds: int = 300
    password_max_failures: int = 5
    lockout_seconds: int = 60
    allowed_roots: list[str] = [
        "~/Documents/JarvisWorkspace",
        "~/Desktop",
        "~/Downloads",
    ]
    delete_preview_threshold: int = 1
    typed_confirmation_for_folders: bool = True


class AppSettings(BaseModel):
    """Allowlist of applications the agent may launch (name -> command)."""

    model_config = ConfigDict(extra="allow")

    notepad: str = "notepad.exe"
    calculator: str = "calc.exe"
    chrome: str = "chrome.exe"


class DaemonSettings(BaseModel):
    """Daemon/IPC settings (used from Phase 3 onwards)."""

    host: str = "127.0.0.1"
    port: int = 0


class VoiceSettings(BaseModel):
    """Voice pipeline settings (used from Phase 5 onwards)."""

    enabled: bool = False
    wake_word: str = "hey_jarvis"
    stt_model: str = "base"
    tts_backend: str = "piper"
    input_device: int | str | None = None
    silence_threshold: float = 0.01
    silence_timeout_s: float = 0.7
    max_segment_s: float = 30.0
    listen_timeout_s: float = 30.0
    idle_timeout_s: float = 120.0
    max_session_s: float = 1800.0
    max_dictation_chars: int = 20000


class Settings(BaseSettings):
    """Top-level application settings.

    Reads ``config.toml`` (path given to the constructor, normally from
    :func:`config_file`) and environment variables prefixed ``JARVIS_``.
    Environment variables take precedence over the file, init kwargs take
    precedence over both (see :meth:`settings_customise_sources`).
    """

    model_config = SettingsConfigDict(
        env_prefix="JARVIS_",
        env_nested_delimiter="__",
        extra="ignore",
    )

    llm: LLMSettings = LLMSettings()
    agent: AgentSettings = AgentSettings()
    policy: PolicySettings = PolicySettings()
    apps: AppSettings = AppSettings()
    daemon: DaemonSettings = DaemonSettings()
    voice: VoiceSettings = VoiceSettings()
    config_version: int = 1

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: Any,
        env_settings: Any,
        dotenv_settings: Any,
        file_secret_settings: Any,
    ) -> tuple[Any, ...]:
        """Add the ``config.toml`` file as a settings source.

        The file path travels as the private ``_toml_file`` init kwarg (set by
        :func:`load_settings`) and is consumed here, so it never leaks into the
        model fields.  Source priority (highest first):

        init kwargs > env vars > dotenv > ``config.toml`` > hard-coded defaults.

        ``TomlConfigSettingsSource`` is available from pydantic-settings >= 2.2;
        this is asserted by ``scripts/verify_env.py``.
        """
        path = init_settings.init_kwargs.pop("_toml_file", None)
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            TomlConfigSettingsSource(settings_cls, toml_file=path),
            file_secret_settings,
        )


def user_data_dir(*parts: str) -> Path:
    """Resolve a path inside the JARVIS data directory.

    ``JARVIS_DATA_DIR`` overrides the platform default (``%LOCALAPPDATA%\\jarvis``
    on Windows) - used by tests and the benchmark runner.
    """
    override = os.environ.get("JARVIS_DATA_DIR")
    base = Path(override) if override else Path(PlatformDirs(APP_NAME, APP_AUTHOR).user_data_dir)
    return base.joinpath(*parts)


def config_file() -> Path:
    """Path to the ``config.toml`` settings file."""
    return user_data_dir("config.toml")


def logs_dir() -> Path:
    """Path to the JARVIS log directory (rotating JSONL files)."""
    return user_data_dir("logs")


def log_file() -> Path:
    """Path to the main JSONL log file."""
    return logs_dir().joinpath("jarvis.jsonl")


def contacts_file() -> Path:
    """Path to the WhatsApp contacts file."""
    return user_data_dir("contacts.json")


def memory_db() -> Path:
    """Path to the skill/failure/preference SQLite database."""
    return user_data_dir("memory.db")


def checkpoints_db() -> Path:
    """Path to the LangGraph checkpoint SQLite database."""
    return user_data_dir("checkpoints.db")


def undo_log() -> Path:
    """Path to the delete undo log."""
    return user_data_dir("undo_log.jsonl")


def reports_dir() -> Path:
    """Path to generated audit reports."""
    return user_data_dir("reports")


def browser_profile_dir() -> Path:
    """Path to the WhatsApp Web persistent browser profile."""
    return user_data_dir("browser_profile")


def daemon_runtime_file() -> Path:
    """Path to the daemon runtime file (pid/port - never secrets)."""
    return user_data_dir("daemon.json")


def load_settings(toml: Path | None = None) -> Settings:
    """Load application settings, optionally from a specific TOML file.

    Defaults to :func:`config_file`. Returns defaults when the file is absent.
    The path is passed as the private ``_toml_file`` init kwarg, which
    :meth:`Settings.settings_customise_sources` turns into the TOML source.
    """
    path = toml if toml is not None else config_file()
    if path.is_file():
        return Settings(_toml_file=str(path))
    return Settings()
