"""Secret storage backed by the system credential store (``keyring``).

API keys, the IPC token, and the Argon2id password hash live in the Windows
Credential Manager (service name ``jarvis``) and are never written to files,
logs, LLM prompts, or checkpoints. Values are never logged by this module.
"""

from __future__ import annotations

import logging

import keyring

logger = logging.getLogger(__name__)

SECRET_SERVICE_NAME = "jarvis"

#: Well-known secret names stored under the service.
SECRET_NAMES: dict[str, str] = {
    "groq_api_key": "Groq API key",
    "openrouter_api_key": "OpenRouter API key",
    "gemini_api_key": "Gemini API key",
    "nvidia_api_key": "NVIDIA API key",
    "tavily_api_key": "Tavily API key",
    "ipc_token": "IPC auth token (generated by `jarvis init`)",
    "password_hash": "Argon2id hash of the JARVIS unlock password (Phase 2)",
    "virustotal_api_key": "VirusTotal API key (optional audit check)",
}

#: Every provider key and its environment-variable fallback(s).  Lookup order is
#: keyring first, then environment, then "missing"; environment variables are
#: read, never copied into the keyring.  A secret without known env vars has no
#: entry here (the IPC token and password hash must never come from the env).
SECRET_ENV_VARS: dict[str, tuple[str, ...]] = {
    "groq_api_key": ("GROQ_API_KEY",),
    "openrouter_api_key": ("OPENROUTER_API_KEY",),
    "gemini_api_key": ("GEMINI_API_KEY", "GOOGLE_API_KEY"),
    "nvidia_api_key": ("NVIDIA_API_KEY",),
    "tavily_api_key": ("TAVILY_API_KEY",),
}

#: Provider short name -> keyring secret name (used by `jarvis keys` and init).
PROVIDER_SECRETS: dict[str, str] = {
    "groq": "groq_api_key",
    "openrouter": "openrouter_api_key",
    "gemini": "gemini_api_key",
    "nvidia": "nvidia_api_key",
    "tavily": "tavily_api_key",
}

# Names that should never be echoed anywhere once a value is known to exist.
REDACTABLE_NAMES = frozenset(SECRET_NAMES)


class SecretStoreError(RuntimeError):
    """Raised when the underlying credential backend fails."""


class SecretStore:
    """Thin, exception-safe wrapper over ``keyring``.

    Every method catches backend failures and converts them into
    :class:`SecretStoreError` so callers (e.g. the CLI) can degrade gracefully.
    """

    def __init__(self, service: str = SECRET_SERVICE_NAME) -> None:
        self._service = service

    def get(self, name: str) -> str | None:
        """Return the stored value, or ``None`` if absent."""
        try:
            return keyring.get_password(self._service, name)
        except keyring.errors.KeyringError as exc:
            logger.warning("keyring get failed for %r: %s", name, type(exc).__name__)
            raise SecretStoreError(
                f"could not read secret {name!r} from the credential store"
            ) from exc

    def set(self, name: str, value: str) -> None:
        """Store a value. Never logs it."""
        try:
            keyring.set_password(self._service, name, value)
        except keyring.errors.KeyringError as exc:
            logger.warning("keyring set failed for %r: %s", name, type(exc).__name__)
            raise SecretStoreError(
                f"could not store secret {name!r} in the credential store"
            ) from exc
        logger.info("stored secret %r in the credential store (%d chars)", name, len(value))

    def delete(self, name: str) -> None:
        """Delete a stored value. Idempotent: missing entries are a no-op."""
        try:
            if keyring.get_password(self._service, name) is None:
                return
            keyring.delete_password(self._service, name)
        except keyring.errors.KeyringError as exc:
            logger.warning("keyring delete failed for %r: %s", name, type(exc).__name__)
            raise SecretStoreError(
                f"could not delete secret {name!r} from the credential store"
            ) from exc
        logger.info("deleted secret %r from the credential store", name)

    def has(self, name: str) -> bool:
        """Return ``True`` when a value exists for ``name``."""
        try:
            return keyring.get_password(self._service, name) is not None
        except keyring.errors.KeyringError as exc:
            logger.warning("keyring probe failed for %r: %s", name, type(exc).__name__)
            raise SecretStoreError(
                f"could not probe secret {name!r} in the credential store"
            ) from exc

    def check_store_access(self) -> str | None:
        """Verify the backend with a named round-trip probe.

        Returns the backend class name on success (e.g. ``WinVaultKeyring``),
        or ``None`` when the credential store is unusable.
        """
        return check_store_access()


def check_store_access() -> str | None:
    """Verify the keyring backend by doing a named round-trip.

    Returns the backend class name on success, or ``None`` on failure. A
    temporary probe entry is written and immediately removed.
    """
    probe = "__jarvis_probe__"
    try:
        backend = keyring.get_keyring()
        from keyring.backend import KeyringBackend

        if not isinstance(backend, KeyringBackend):
            return None
        keyring.set_password(SECRET_SERVICE_NAME, probe, "probe")
        got = keyring.get_password(SECRET_SERVICE_NAME, probe)
        keyring.delete_password(SECRET_SERVICE_NAME, probe)
        return type(backend).__name__ if got == "probe" else None
    except Exception:  # noqa: BLE001 - any backend failure means "cannot store secrets"
        return None
